version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    environment:
      - GOPATH: /home/circleci/go

    working_directory: /home/circleci/go/src/github.com/gunkan-s/barnament
    steps:
      - run: echo 'export PATH=${GOPATH}/bin/:${PATH}' >> $BASH_ENV
      - checkout
      - run: go get -v -t -d ./...
